---
title: "ODE with Jacobian"
output: html_notebook
---

## Solving with C 
This is the C module. It is saved as `mymod.c`.
We will compile it below:

```
/* file mymod.c */
#include <R.h>
static double parms[3];
#define k1 parms[0]
#define k2 parms[1]
#define k3 parms[2]

/* initializer  */
void initmod(void (* odeparms)(int *, double *))
{
    int N=3;
    odeparms(&N, parms);
}

/* Derivatives and 1 output variable */
void derivs (int *neq, double *t, double *y, double *ydot,
             double *yout, int *ip)
{
    if (ip[0] <1) error("nout should be at least 1");
    ydot[0] = -k1*y[0] + k2*y[1]*y[2];
    ydot[2] = k3 * y[1]*y[1];
    ydot[1] = -ydot[0]-ydot[2];

    yout[0] = y[0]+y[1]+y[2];
}

/* The Jacobian matrix */
void jac(int *neq, double *t, double *y, int *ml, int *mu,
           double *pd, int *nrowpd, double *yout, int *ip)
{
  pd[0]               = -k1;
  pd[1]               = k1;
  pd[2]               = 0.0;
  pd[(*nrowpd)]       = k2*y[2];
  pd[(*nrowpd) + 1]   = -k2*y[2] - 2*k3*y[1];
  pd[(*nrowpd) + 2]   = 2*k3*y[1];
  pd[(*nrowpd)*2]     = k2*y[1];
  pd[2*(*nrowpd) + 1] = -k2 * y[1];
  pd[2*(*nrowpd) + 2] = 0.0;
}
/* END file mymod.c */

```

### Compiling the `C` module
```{r}
# Unload if the the module is loaded
if(is.loaded("mymod")) dyn.unload(paste("mymod", .Platform$dynlib.ext, sep = ""))
# delete any existing files first
file.remove("mymod.o")
file.remove("mymod.dll")
file.remove("mymod.so")

# now, compile
system("R CMD SHLIB mymod.c")
```


### Build the DE model and Jacobian in pure R
```{r}
library(deSolve)


model <- function(t, Y, parameters) {
  with (as.list(parameters),{

    dy1 = -k1*Y[1] + k2*Y[2]*Y[3]
    dy3 = k3*Y[2]*Y[2]
    dy2 = -dy1 - dy3

    list(c(dy1, dy2, dy3))
  })
}


jac <- function (t, Y, parameters) {
  with (as.list(parameters),{

    PD[1,1] <- -k1
    PD[1,2] <- k2*Y[3]
    PD[1,3] <- k2*Y[2]
    PD[2,1] <- k1
    PD[2,3] <- -PD[1,3]
    PD[3,2] <- k3*Y[2]
    PD[2,2] <- -PD[1,2] - PD[3,2]

    return(PD)
  })
}

```

```{r}


parms <- c(k1 = 0.04, k2 = 1e4, k3 = 3e7)
Y     <- c(1.0, 0.0, 0.0)
times <- c(0, 0.4*10^(0:11))

PD    <- matrix(nrow = 30, ncol = 30, data = 0)

out   <- ode(Y, times, model, parms = parms, jacfunc = jac)

plot(out)


# system("R CMD SHLIB mymod.c")

dyn.load(paste("mymod", .Platform$dynlib.ext, sep = ""))

## benchmarks
lim <- 100

system.time(
  for(i in 1:lim) out   <- ode(Y, times, model, parms = parms)
)

system.time(
  for(i in 1:lim) out   <- ode(Y, times, model, parms = parms, jacfunc = jac)
)

system.time(
  for(i in 1:lim)
    out <- ode(Y, times, func = "derivs", parms = parms,
               dllname = "mymod",
               initfunc = "initmod", nout = 1, outnames = "Sum")
)

system.time(
  for(i in 1:lim)
    out <- ode(Y, times, func = "derivs", parms = parms,
               jacfunc = "jac", dllname = "mymod",
               initfunc = "initmod", nout = 1, outnames = "Sum")
)
```

